
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: my_mysql
  password: welcome1
  host: my_mysql

development:
  <<: *default
  database: my_development


test:
  <<: *default
  database: my_test

production:
  <<: *default
  database: my_production
  username: welcome1
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
